[package]
name = "noise_engine_native"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
libc = "0.2.65"
once_cell = "1.15.0"
ash = "0.37.0"
enumflags2 = "0.7.5"
uuid = "1.2.1"
lockfree = "0.5.1"
rsevents = "0.3.1"
gpu-alloc = "0.5.3"
gpu-alloc-ash = "0.5.0"
