using NoiseEngine.Nesl.CompilerTools.Parsing.Expressions;

namespace NoiseEngine.Nesl;

public enum CompilationErrorType {
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    None = 0,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    UnexpectedExpression,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedTypeIdentifier,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    MissingName,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedUsing,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedOperatorKeyword,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedReturn,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedSemicolon,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedComma,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedOpeningRoundBracket,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedClosingRoundBracket,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedOpeningCurlyBracket,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedClosingCurlyBracket,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedOpeningAngleBracket,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedClosingAngleBracket,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedOpeningSquareBracket,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedClosingSquareBracket,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedOperator,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedValue,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedTypeKind,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedExplicitCastNotValue,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedExplicitCastNotExpression,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedAssignmentOperator,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedAttribute,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedConstValue,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedNumber,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedInt64,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedInt32,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedInt16,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedInt8,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedUInt64,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedUInt32,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedUInt16,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedUInt8,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedFloat64,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedFloat32,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedFloat16,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedBool,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedString,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedQuotationMark,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedGenericParameter,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedGetter,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedInitializerOrSetter,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedAssignmentExpression,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedIndexer,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedWhereKeyword,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    InvalidTypeKind,
    [CompilationErrorType(CompilationErrorSeverity.Warning)]
    UsingAlreadyExists,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    TypeAlreadyExists,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    FieldOrPropertyOrIndexerAlreadyExists,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    MethodAlreadyExists,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ParameterAlreadyExists,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    UsingNotFound,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    TypeNotFound,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    FieldNotFound,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    MethodNotFound,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    MethodWithGivenArgumentsNotFound,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ConstructorNotFound,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    AttributeNotFound,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    AttributeCreateMethodNotFound,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    VariableOrFieldOrPropertyNotFound,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    IndexerNotFound,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ImplicitCastOperatorNotFound,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    GenericParameterNotFound,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    OperatorNotFound,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    UsingGenericNotAllowed,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    AttributeGenericNotAllowed,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    AssignmentGenericNotAllowed,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ConstraintGenericParameterNotAllowed,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    InitializerForIndexerNotAllowed,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ThisNameForFieldOrPropertyNotAllowed,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    LeftOperatorNotAllowed,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    OperatorNotAllowed,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    FieldInInterfaceNotAllowed,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ConstructorInInterfaceNotAllowed,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    UniformMethodNotAllowed,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    AbstractMethodMustBeInInterface,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    InheritanceTypeMustBeAInterface,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ConstraintTypeMustBeAInterface,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    AttributeTargetNotMatch,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    SubtractionOperatorNotMatchExpression,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    AssignmentExpressionCannotBeNew,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    AssignmentExpressionCannotBeMethod,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    AbstractMethodNotImplemented,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    TypeNotSatisfiedGenericConstraint
}
