using NoiseEngine.Nesl.CompilerTools.Parsing.Expressions;

namespace NoiseEngine.Nesl;

public enum CompilationErrorType {
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    None = 0,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    UnexpectedExpression,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedTypeIdentifier,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    MissingName,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedUsing,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedReturn,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedSemicolon,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedComma,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedOpeningRoundBracket,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedClosingRoundBracket,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedOpeningCurlyBracket,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedClosingCurlyBracket,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedOpeningAngleBracket,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedClosingAngleBracket,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedOpeningSquareBracket,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedClosingSquareBracket,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedOperator,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedValue,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedTypeKind,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedExplicitCastNotValue,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedExplicitCastNotExpression,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedAssigmentOperator,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedAttribute,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedConstValue,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedNumber,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedInt64,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedInt32,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedInt16,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedInt8,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedUInt64,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedUInt32,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedUInt16,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedUInt8,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedFloat64,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedFloat32,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedFloat16,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedBool,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedString,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedQuotationMark,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedGenericParameter,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ExpectedGetter,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    InvalidTypeKind,
    [CompilationErrorType(CompilationErrorSeverity.Warning)]
    UsingAlreadyExists,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    TypeAlreadyExists,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    FieldOrPropertyAlreadyExists,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    MethodAlreadyExists,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ParameterAlreadyExists,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    UsingNotFound,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    TypeNotFound,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    FieldNotFound,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    MethodNotFound,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    MethodWithGivenArgumentsNotFound,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ConstructorNotFound,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    AttributeNotFound,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    AttributeCreateMethodNotFound,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    VariableOrFieldOrPropertyNotFound,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    ImplicitCastOperatorNotFound,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    UsingGenericNotAllowed,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    AttributeGenericNotAllowed,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    AssigmentGenericNotAllowed,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    AttributeTargetNotMatch,
    [CompilationErrorType(CompilationErrorSeverity.Error)]
    SubtractionOperatorNotMatchExpression,
}
