name: Tests

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - master
      - release-*
      - dev-*

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.x.x'
        include-prerelease: true
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore /p:DoNotBuildMainNative=true
    - name: Run tests
      run: dotnet test --no-build --verbosity normal
      timeout-minutes: 1
      env:
        NOISEENGINE_NO_SUPPORTS: gpu;gui;
